name = "Vanilla Optimized"
author = "chizusrevenge"
version = "2.9.1-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ace642bb12ff74629d1849b3de4c86af5d92448da93b1e88f60e476f422beb87"

[versions]
fabric = "0.16.0"
minecraft = "1.21"

[options]
acceptable-game-versions = ["1.20.6"]
