name = "Vortexial Optimized"
author = "chizusrevenge"
version = "2.1.4-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "786bb16e0dfedc0331319b78214f7951da5ff9ca1ec3e152d22876990067a25d"

[versions]
fabric = "0.16.3"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
