name = "Vortexial Optimized"
author = "chizusrevenge"
version = "2.1.6-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ddf4210e3734f84df87010504c6dbe7b697d01be567e8fb01f23f1a5940798f3"

[versions]
fabric = "0.16.4"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
