name = "Vortexial Optimized"
author = "chizusrevenge"
version = "2.1.1-alpha"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "08de9600a7622cbbde94cad7b70068b083b861d854093d3c3c2233f47a035162"

[versions]
fabric = "0.16.0"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
