name = "Vortexial Optimized"
author = "chizusrevenge"
version = "2.1.2-alpha"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9fb92e6db2e36b15d9428d0d14267b664333c2af84cbec13069d4ac203e7ba50"

[versions]
fabric = "0.16.0"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
