name = "Vanilla Optimized"
author = "chizusrevenge"
version = "1.3.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "af7a44a3ca3d4e7ba107536c2000be0d9c396ad5f35d98d2bc9ef26c013fecdd"

[versions]
fabric = "0.15.11"
minecraft = "1.20.4"
