name = "Vortexial Optimized"
author = "chizusrevenge"
version = "2.1.4-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c56b8d729f850326abc64401cb0c4ffd69531a8744a6ff5a5878264c90346a81"

[versions]
fabric = "0.16.3"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
