name: Automatically publish to Modrinth and CurseForge

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-22.04
    concurrency:
      group: publish-release
      cancel-in-progress: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Get latest release info
        id: get_release
        run: |
          latest_release=$(curl -s https://api.github.com/repos/${{ github.repository }}/releases/latest)
          echo "tag_name=$(echo $latest_release | jq -r .tag_name)" >> $GITHUB_ENV
          echo "changelog=$(echo $latest_release | jq -r .body)" >> $GITHUB_ENV
          for asset_url in $(echo $latest_release | jq -r '.assets[].browser_download_url'); do
            asset_name=$(basename $asset_url)
            echo "Downloading $asset_name from $asset_url"
            curl -L $asset_url -o $asset_name
          done

      - name: Publish to Modrinth
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: oXpnIe9R
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          files: |
            Vortexial.Optimized-${{ vars.version }}.mrpack
          name: ${{ vars.version }} for ${{ vars.GAME_VERSION }}
          changelog: ${{ vars.CHANGELOG }}
          loaders: fabric
          game-versions: ${{ vars.GAME_VERSION }}

      - name: Publish to CurseForge
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          name: ${{ vars.version }} for ${{ vars.GAME_VERSION }}
          curseforge-id: 1069886
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          curseforge-files: |
            Vortexial.Optimized-${{ vars.version }}.zip
          loaders: fabric
          game-versions: ${{ vars.GAME_VERSION }}
          changelog: ${{ vars.CHANGELOG }}
